# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "debian/buster64"
    config.vbguest.auto_update = false
    # config.vm.synced_folder "../data", "/data"

    # Provision basic tools to installation
    config.vm.provision "shell", path: "provision-tools-basic.sh", privileged: true

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 6144
        vb.cpus = 4
    end

end
